---
name: CI
on: [push, pull_request]
jobs:
  build:
    uses: pkgjs/action/.github/workflows/node-test.yaml@main
    with:
      post-install-steps: 'npm run lint'

  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.7.1
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
